src/CMS/Bundle/AdminBundle/Form/PageType.php
<?php

namespace CMS\Bundle\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use CMS\Bundle\AdminBundle\Repository\PageRepository;

/**
 * page type controller
 */
class PageType extends AbstractType
{
    private $templates;

    /**
     * Construct
     *
     * @param type $templates
     */
    public function __construct($templates)
    {
        $this->templates = $templates;
    }

    /**
     * @param \Symfony\Component\Form\FormBuilderInterface $builder Builder
     * @param array                                        $options Options Form
     *
     * @return type
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('parent', 'entity', array(
                'required' => true,
                'class' => 'CMSAdminBundle:Page',
                'query_builder' => function (PageRepository $pRe) {
                    return $pRe->createQueryBuilder('p')
                        ->orderBy('p.lft', 'ASC');
                }
            ))
            ->add('active')
            ->add('media_id', null, array('required' => false))
            ->add('type', 'choice', array(
                'choices' => $this->templates,
                'required' => true
            ))
            ->add('is_home')
            ->add('is_showreel')
            ->add('page_languages', 'collection', array(
                'type' => new PageLanguageType()
            ));
    }

    /**
     * @param \Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\Bundle\AdminBundle\Entity\Page'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'cms_bundle_adminbundle_pagetype';
    }
}

src/CMS/Bundle/AdminBundle/Resources/views/Page/edit.html.twig
{% extends 'CMSAdminBundle::admin.html.twig' %}
{% block body %}
<h1>Page creation</h1>

<form action="{{ path('admin_page_edit', {'id' : entity.id}) }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.parent) }}</label>
            <div class="controls">
                {{ form_errors(form.parent) }}
                {{ form_widget(form.parent) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.active) }}</label>
            <div class="controls">
                {{ form_errors(form.active) }}
                {{ form_widget(form.active) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="optionsCheckbox">{{ form_label(form.media_id) }}</label>
            <div class="controls">
              <label class="checkbox">
                    {{ form_errors(form.media_id) }}
                    {{ form_widget(form.media_id, {'attr': {'style': 'display: none'} }) }}
                    {% set selectName = form.media_id.get('full_name') %}
                    {{ CMSmedia(optMedias, selectName, mediaPath)|raw() }}
              </label>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.type) }}</label>
            <div class="controls">
                {{ form_errors(form.type) }}
                {{ form_widget(form.type) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.is_home) }}</label>
            <div class="controls">
                {{ form_errors(form.is_home) }}
                {{ form_widget(form.is_home) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.is_showreel) }}</label>
            <div class="controls">
                {{ form_errors(form.is_showreel) }}
                {{ form_widget(form.is_showreel) }}
            </div>
        </div>

        <hr />

        <div class="tabbable"> <!-- Only required for left/right tabs -->
            <ul class="nav nav-tabs">
                  {% set isActive = 1 %}
                  {% for lang in langList %}
                      {% if isActive == 1%}
                          <li class="active"><a href="#tab{{ lang.id }}" data-toggle="tab">{{ lang.name }}</a></li>
                      {% else %}
                          <li><a href="#tab{{ lang.id }}" data-toggle="tab">{{ lang.name }}</a></li>
                      {% endif %}
                      {% set isActive = 2 %}
                  {% endfor %}
            </ul>
            <div class="tab-content">
                {% set isActive = 1 %}
                {% for lang in langList %}
                    {% set currentAL = null %}
                    {% for pageLanguage in form.page_languages%}
                        {% if pageLanguage.vars.value.language.id == lang.id %}
                            {% set currentAL = pageLanguage %}
                        {% endif%}
                    {% endfor %}
                    {% if isActive == 1%}
                        <div class="tab-pane active" id="tab{{ lang.id }}">
                    {% else %}
                        <div class="tab-pane" id="tab{{ lang.id }}">
                    {% endif %}
                            <fieldset>
                                {% if currentAL is not null %}
                                <div class="control-group">
                                    <label class="control-label" for="input01">{{ form_label(currentAL.name) }}</label>
                                    <div class="controls">
                                        {{ form_errors(currentAL.name) }}
                                        {% if defaultLanguage.name == currentAL.vars.value.language.name %}
                                            {{ form_widget(currentAL.name, {'attr': {'required': 'required'}}) }}
                                        {% else %}
                                            {{ form_widget(currentAL.name) }}
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="input01">{{ form_label(currentAL.description) }}</label>
                                    <div class="controls">
                                        {{ form_errors(currentAL.description) }}
                                        {{ form_widget(currentAL.description) }}
                                    </div>
                                </div>
                                {% endif%}
                            </fieldset>
                        </div>
                    {% set isActive = 2 %}
               {% endfor %}
            </div>
        </div>

        <div class="form-actions">
            {{ form_row(form._token) }}
            <button type="submit" class="btn btn-primary">Save changes</button>
            <a href="{{ path('admin_page', {'page' : 1}) }}" class="btn">Back To List</a>
        </div>

    </fieldset>
</form>

{% endblock %}

src/CMS/Bundle/AdminBundle/Resources/views/Page/index.html.twig
{% extends 'CMSAdminBundle::admin.html.twig' %}
{% block body%}
<h1>Page list</h1>
<div class="nav">
    <a href="{{ path('admin_page_new') }}" class="btn btn-primary">Create a new entry</a>
    <div class="btn-group pull-right">
        <a href="javascript:void(0)" data-toggle="dropdown" class="btn btn-primary dropdown-toggle">
            {% for opt in langList %}
                {% if lang == opt.id %}
                {{ opt.name }} <span class="caret"></span>
                {% endif %}
            {% endfor %}
        </a>
        <ul class="dropdown-menu">
            {% for opt in langList %}
                <li><a href="{{ path('admin_page', {'page': 1, 'lang' : opt.id }) }}">{{ opt.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th style="width: 14px;">&nbsp;</th>
            <th>Background</th>
            <th style="width: 100px;">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for entity in entities %}
        {% if entity.parent is not null %}
        <tr>
            <td>{{ entity.id }}</td>
            <td>
                {% if entity.getCurrentPageLanguage is not null %}
                {{ entity.getCurrentPageLanguage.getTreeName | truncate(50) }}
                {% else %}
                <span class="label label-warning">{{ 'Not set value in this language' | trans({}, 'CMSAdminBundle') }}</span>
                {% endif %}
            </td>
            <td>
                {% if entity.parent.children is defined %}
                {% if entity.parent.children[0].id != entity.id %}
                    <a href="{{ path('admin_page_up', { 'id': entity.id}) }}">
                        <i class="icon-arrow-up"></i>
                    </a>
                {% endif %}
                {% if entity.parent.children[entity.parent.children|length-1].id != entity.id %}
                    <a class="pull-right" href="{{ path('admin_page_down', { 'id': entity.id}) }}">
                        <i class="icon-arrow-down"></i>
                    </a>
                {% endif %}
                {% endif %}
            </td>
            <td>
                {% if entity.mediaId[0].name is defined %}
                    <image src="/uploads/{{ entity.mediaId[0].name }}" width="100px" height="100px"/>
                {% endif %}
            </td>
            <td>
                {#<a href="{{ path('admin_page_show', { 'id': entity.page.id }) }}">show</a>
                &nbsp; | &nbsp;
                #}
                <a href="{{ path('admin_page_edit', { 'id': entity.id }) }}">edit</a>

                {% if entity.getCurrentPageLanguage is not null %}
                    &nbsp; | &nbsp;
                    <a class="delete" href="#" rel="{{ path('admin_page_delete', { 'id': entity.getCurrentPageLanguage.id }) }}">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

{# Pagination for list #}
{% if lastPage > 1 %}
<div class="pagination" style="text-align: right;">
    <ul>
        <li><a href="{{ path('admin_page', { 'page': 1, 'lang' : lang }) }}">«</a></li>
        <li><a href="{{ path('admin_page', { 'page': previousPage, 'lang' : lang }) }}">Previous</a></li>
    {% for page in 1..lastPage %}
      {% if page == currentPage %}
        <li class="active"><a href="{{ path('admin_page', {'page': page, 'lang' : lang }) }}">{{ page }}</a></li>
      {% else %}
        <li><a href="{{ path('admin_page', {'page': page, 'lang' : lang } )}}">{{ page }}</a></li>
      {% endif %}
    {% endfor %}
        <li><a href="{{ path('admin_page', {'page': nextPage, 'lang' : lang }) }}">Next</a></li>
        <li><a href="{{ path('admin_page', {'page': lastPage, 'lang' : lang }) }}">»</a></li>
    </ul>
</div>
{% endif %}

{% endblock %}

src/CMS/Bundle/AdminBundle/Resources/views/Page/new.html.twig
{% extends 'CMSAdminBundle::admin.html.twig' %}
{% block body %}
<h1>Page creation</h1>

<form action="{{ path('admin_page_new') }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.parent) }}</label>
            <div class="controls">
                {{ form_errors(form.parent) }}
                {{ form_widget(form.parent) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.active) }}</label>
            <div class="controls">
                {{ form_errors(form.active) }}
                {{ form_widget(form.active) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="optionsCheckbox">{{ form_label(form.media_id) }}</label>
            <div class="controls">
              <label class="checkbox">
                    {{ form_errors(form.media_id) }}
                    {{ form_widget(form.media_id, {'attr': {'style': 'display: none'} }) }}
                    {% set selectName = form.media_id.get('full_name') %}
                    {{ CMSmedia(optMedias, selectName, mediaPath)|raw() }}
              </label>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.type) }}</label>
            <div class="controls">
                {{ form_errors(form.type) }}
                {{ form_widget(form.type) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.is_home) }}</label>
            <div class="controls">
                {{ form_errors(form.is_home) }}
                {{ form_widget(form.is_home) }}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">{{ form_label(form.is_showreel) }}</label>
            <div class="controls">
                {{ form_errors(form.is_showreel) }}
                {{ form_widget(form.is_showreel) }}
            </div>
        </div>

        <hr />

        <div class="tabbable"> <!-- Only required for left/right tabs -->
            <ul class="nav nav-tabs">
                  {% set isActive = 1 %}
                  {% for lang in langList %}
                      {% if isActive == 1%}
                          <li class="active"><a href="#tab{{ lang.id }}" data-toggle="tab">{{ lang.name }}</a></li>
                      {% else %}
                          <li><a href="#tab{{ lang.id }}" data-toggle="tab">{{ lang.name }}</a></li>
                      {% endif %}
                      {% set isActive = 2 %}
                  {% endfor %}
            </ul>
            <div class="tab-content">
                {% set isActive = 1 %}
                {% for pageLanguage in form.page_languages %}
                    {% if isActive == 1%}
                        <div class="tab-pane active" id="tab{{ langList[loop.index0].id }}">
                    {% else %}
                        <div class="tab-pane" id="tab{{ langList[loop.index0].id }}">
                    {% endif %}
                            <fieldset>

                                <div class="control-group">
                                    <label class="control-label" for="input01">{{ form_label(pageLanguage.name) }}</label>
                                    <div class="controls">
                                        {{ form_errors(pageLanguage.name) }}
                                        {% if defaultLanguage.name == pageLanguage.vars.value.language.name %}
                                            {{ form_widget(pageLanguage.name, {'attr': {'required': 'required'}}) }}
                                        {% else %}
                                            {{ form_widget(pageLanguage.name) }}
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label class="control-label" for="input01">{{ form_label(pageLanguage.description) }}</label>
                                    <div class="controls">
                                        {{ form_errors(pageLanguage.description) }}
                                        {{ form_widget(pageLanguage.description) }}
                                    </div>
                                </div>

                            </fieldset>
                        </div>
                    {% set isActive = 2 %}
               {% endfor %}
            </div>
        </div>

        <div class="form-actions">
            {{ form_row(form._token) }}
            <button type="submit" class="btn btn-primary">Save changes</button>
            <a href="{{ path('admin_page', {'page' : 1}) }}" class="btn">Back To List</a>
        </div>

    </fieldset>
</form>

{% endblock %}

src/CMS/Bundle/AdminBundle/Resources/views/Page/show.html.twig
{% extends 'CMSAdminBundle::admin.html.twig' %}
{% block body %}
<h1>Page</h1>
<hr />
<table>
    <tr>
        <td>Parent</td>
        <td>
            {% if entity.parent.id is defined %}
                {{ entity.parent.id }}
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>Background</td>
        <td>
            {% if entity.mediaId[0].name is defined %}
                <image src="/uploads/{{ entity.mediaId[0].name }}" width="100px" height="100px"/>
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>Active</td>
        <td>
            {% if entity.active == 1 %}
                <input type="checkbox" name="active" checked="checked" disabled="true"/>
            {% else %}
                <input type="checkbox" name="active" disabled="true"/>
            {% endif%}
        </td>
    </tr>
</table>

<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
        {% set isActive = 1 %}
        {% for lang in langList %}
            {% if isActive == 1%}
                <li class="active"><a href="#tab{{ lang.id }}" data-toggle="tab">{{ lang.name }}</a></li>
            {% else %}
                <li><a href="#tab{{ lang.id }}" data-toggle="tab">{{ lang.name }}</a></li>
            {% endif %}
            {% set isActive = 2 %}
        {% endfor %}
  </ul>
    <div class="tab-content">
        {% set isActive = 1 %}
        {% for lang in langList %}
            {% if isActive == 1%}
                <div class="tab-pane active" id="tab{{ lang.id }}">
            {% else %}
                <div class="tab-pane" id="tab{{ lang.id }}">
            {% endif %}
                        <table>
                            <tr>
                                <td>Name</td>
                                <td>
                                    {% if rstPageLang[lang.id][0] is defined %}
                                        {{ rstPageLang[lang.id][0].name}}
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td>
                                    {% if rstPageLang[lang.id][0] is defined %}
                                        {{ rstPageLang[lang.id][0].description}}
                                    {% endif %}

                                </td>
                            </tr>
                        </table>
                </div>
            {% set isActive = 2 %}
       {% endfor %}
    </div>
</div>

<hr />
<div class="form-actions">
    <a href="{{ path('admin_page', {'page' : 1}) }}" class="btn">Back To List</a>
    &nbsp;
    <a href="{{ path('admin_page_edit', { 'id': entity.id }) }}" class="btn">edit</a>
</div>

</form>
{% endblock %}